import { ProductionOrder, MillLine } from "@/types/millProduction";

const mockOrders: ProductionOrder[] = [
  // === PREMIX ORDERS (11) ===
  // Premix Completed (5)
  {
    id: "1",
    orderNumber: "ORD-255154",
    customer: "Westbridge Farm",
    product: "BROILER BRD 16% OS",
    weightLbs: 6000,
    deliveryTime: "6:30 AM",
    state: "Completed",
    millLine: "Premix",
    textureType: "MASH",
    lineCode: "33161",
  },
  {
    id: "2",
    orderNumber: "ORD-255177",
    customer: "Meadowview Poultry",
    product: "BROILER BRD 15% OS",
    weightLbs: 9000,
    deliveryTime: "7:00 AM",
    state: "Completed",
    millLine: "Premix",
    textureType: "MASH",
    lineCode: "33177",
  },
  {
    id: "3",
    orderNumber: "ORD-255492",
    customer: "Starbird @ Jaedel",
    product: "BROILER BRD LAY 1 T8",
    weightLbs: 12000,
    deliveryTime: "7:30 AM",
    state: "Completed",
    millLine: "Premix",
    textureType: "MASH",
    lineCode: "33260",
  },
  {
    id: "4",
    orderNumber: "ORD-255437",
    customer: "Severinski Farm",
    product: "LAYER BRD DEV 11-16WKS MASH",
    weightLbs: 5000,
    deliveryTime: "8:00 AM",
    state: "Completed",
    millLine: "Premix",
    textureType: "MASH",
    lineCode: "17003",
  },
  {
    id: "5",
    orderNumber: "ORD-255255",
    customer: "Jireh Farms",
    product: "LAY 1 FREE RANGE OS",
    weightLbs: 6000,
    deliveryTime: "8:30 AM",
    state: "Completed",
    millLine: "Premix",
    textureType: "MASH",
    lineCode: "16796",
  },
  // Premix Pending (3)
  {
    id: "6",
    orderNumber: "ORD-255491",
    customer: "Corner's Pride Farm",
    product: "BRD DEVELOP PLAIN T8",
    weightLbs: 8000,
    deliveryTime: "11:30 AM",
    state: "Pending",
    millLine: "Premix",
    textureType: "MASH",
    lineCode: "33248",
  },
  {
    id: "7",
    orderNumber: "ORD-255403",
    customer: "Trilean Makin Bacon",
    product: "LAY 2 MASH",
    weightLbs: 12000,
    deliveryTime: "1:00 PM",
    state: "Pending",
    millLine: "Premix",
    textureType: "MASH",
    lineCode: "16590",
  },
  {
    id: "8",
    orderNumber: "ORD-255477",
    customer: "Rockwall @ Peardonville",
    product: "LAY 1 MASH",
    weightLbs: 3000,
    deliveryTime: "2:30 PM",
    state: "Pending",
    millLine: "Premix",
    textureType: "MASH",
    lineCode: "16595",
  },
  // Premix Mixing (2)
  {
    id: "9",
    orderNumber: "ORD-255421",
    customer: "Cedarcroft Poultry",
    product: "BRD PRE-START FINE CR",
    weightLbs: 6000,
    deliveryTime: "9:15 AM",
    state: "Mixing",
    millLine: "Premix",
    textureType: "FINE CR",
    lineCode: "33101",
  },
  {
    id: "10",
    orderNumber: "ORD-255400",
    customer: "Triple H Farms",
    product: "OMEGA VEG LAY 1 MASH",
    weightLbs: 6000,
    deliveryTime: "10:00 AM",
    state: "Mixing",
    millLine: "Premix",
    textureType: "MASH",
    lineCode: "16361",
  },
  // Premix Blocked (1)
  {
    id: "11",
    orderNumber: "ORD-255257",
    customer: "Whytebridge Farms",
    product: "LAY 5 FREE RANGE OS",
    weightLbs: 15000,
    deliveryTime: "9:45 AM",
    state: "Blocked",
    millLine: "Premix",
    textureType: "MASH",
    lineCode: "16777",
  },

  // === EXCEL ORDERS (11) ===
  // Excel Completed (5)
  {
    id: "12",
    orderNumber: "ORD-255298",
    customer: "Westbridge Farm",
    product: "MOOLICIOUS DAIRY MASH",
    weightLbs: 15000,
    deliveryTime: "7:00 AM",
    state: "Completed",
    millLine: "Excel",
    textureType: "MASH",
    lineCode: "66218",
  },
  {
    id: "13",
    orderNumber: "ORD-255309",
    customer: "Meadowview Poultry",
    product: "HOLY COW COMPUTER PELLET",
    weightLbs: 6000,
    deliveryTime: "7:45 AM",
    state: "Completed",
    millLine: "Excel",
    textureType: "PELLET",
    lineCode: "66393",
  },
  {
    id: "14",
    orderNumber: "ORD-255279",
    customer: "Starbird @ Jaedel",
    product: "UDDERLY DAIRY MASH",
    weightLbs: 4000,
    deliveryTime: "8:15 AM",
    state: "Completed",
    millLine: "Excel",
    textureType: "MASH",
    lineCode: "66554",
  },
  {
    id: "15",
    orderNumber: "ORD-255307",
    customer: "Severinski Farm",
    product: "17% ROBOT PELLET",
    weightLbs: 3000,
    deliveryTime: "8:45 AM",
    state: "Completed",
    millLine: "Excel",
    textureType: "PELLET",
    lineCode: "66000",
  },
  {
    id: "16",
    orderNumber: "ORD-255297",
    customer: "Jireh Farms",
    product: "DAIRY GODMOTHER MASH",
    weightLbs: 4000,
    deliveryTime: "9:00 AM",
    state: "Completed",
    millLine: "Excel",
    textureType: "MASH",
    lineCode: "66766",
  },
  // Excel Pending (3)
  {
    id: "17",
    orderNumber: "ORD-255447",
    customer: "Corner's Pride Farm",
    product: "FINISHER FEB 2026 WHEY",
    weightLbs: 6000,
    deliveryTime: "1:00 PM",
    state: "Pending",
    millLine: "Excel",
    textureType: "PELLET",
    lineCode: "44114",
  },
  {
    id: "18",
    orderNumber: "ORD-255445",
    customer: "Trilean Makin Bacon",
    product: "PREGROW 1 JUNE 2025",
    weightLbs: 3000,
    deliveryTime: "1:30 PM",
    state: "Pending",
    millLine: "Excel",
    textureType: "PELLET",
    lineCode: "44139M",
  },
  {
    id: "19",
    orderNumber: "ORD-255306",
    customer: "Rockwall @ Peardonville",
    product: "GOT MILK DAIRY MASH",
    weightLbs: 9000,
    deliveryTime: "2:00 PM",
    state: "Pending",
    millLine: "Excel",
    textureType: "MASH",
    lineCode: "66124",
  },
  // Excel Mixing (2)
  {
    id: "20",
    orderNumber: "ORD-255300",
    customer: "Cedarcroft Poultry",
    product: "LEGENDAIRY ROBOT GRAIN PELLET",
    weightLbs: 18000,
    deliveryTime: "10:30 AM",
    state: "Mixing",
    millLine: "Excel",
    textureType: "PELLET",
    lineCode: "66353",
  },
  {
    id: "21",
    orderNumber: "ORD-255308",
    customer: "Triple H Farms",
    product: "MILKY WAY DAIRY SUPP",
    weightLbs: 6000,
    deliveryTime: "11:00 AM",
    state: "Mixing",
    millLine: "Excel",
    textureType: "MASH",
    lineCode: "66180",
  },
  // Excel Blocked (1)
  {
    id: "22",
    orderNumber: "ORD-255299",
    customer: "Whytebridge Farms",
    product: "CORN75/BARLEY25",
    weightLbs: 6000,
    deliveryTime: "10:00 AM",
    state: "Blocked",
    millLine: "Excel",
    textureType: "MASH",
    lineCode: "65623",
  },

  // === CGM ORDERS (11) ===
  // CGM Completed (5)
  {
    id: "23",
    orderNumber: "ORD-255393",
    customer: "Westbridge Farm",
    product: "BROILER GROWER I MD",
    weightLbs: 15000,
    deliveryTime: "6:30 AM",
    state: "Completed",
    millLine: "CGM",
    textureType: "SH PELLET",
    lineCode: "22563",
  },
  {
    id: "24",
    orderNumber: "ORD-255396",
    customer: "Meadowview Poultry",
    product: "BROILER GROWER I MD",
    weightLbs: 9000,
    deliveryTime: "7:00 AM",
    state: "Completed",
    millLine: "CGM",
    textureType: "SH PELLET",
    lineCode: "22563",
  },
  {
    id: "25",
    orderNumber: "ORD-255383",
    customer: "Starbird @ Jaedel",
    product: "BROILER PRESTART FINE CR FG",
    weightLbs: 15000,
    deliveryTime: "7:30 AM",
    state: "Completed",
    millLine: "CGM",
    textureType: "FINE CR",
    lineCode: "22151",
  },
  {
    id: "26",
    orderNumber: "ORD-255428",
    customer: "Severinski Farm",
    product: "LAYER BRD PH 2 CR",
    weightLbs: 3000,
    deliveryTime: "8:00 AM",
    state: "Completed",
    millLine: "CGM",
    textureType: "C. CRUMBLE",
    lineCode: "17106",
  },
  {
    id: "27",
    orderNumber: "ORD-255191",
    customer: "Jireh Farms",
    product: "BROILER PRESTART FINE CR",
    weightLbs: 18000,
    deliveryTime: "8:30 AM",
    state: "Completed",
    millLine: "CGM",
    textureType: "FINE CR",
    lineCode: "22561",
  },
  // CGM Pending (3)
  {
    id: "28",
    orderNumber: "ORD-255392",
    customer: "Corner's Pride Farm",
    product: "BROILER GROWER 2 MD",
    weightLbs: 15000,
    deliveryTime: "2:30 PM",
    state: "Pending",
    millLine: "CGM",
    textureType: "PELLET",
    lineCode: "22564",
  },
  {
    id: "29",
    orderNumber: "ORD-255329",
    customer: "Trilean Makin Bacon",
    product: "BROILER PRESTART FINE CR",
    weightLbs: 21000,
    deliveryTime: "2:45 PM",
    state: "Pending",
    millLine: "CGM",
    textureType: "FINE CR",
    lineCode: "22561",
  },
  {
    id: "30",
    orderNumber: "ORD-255343",
    customer: "Rockwall @ Peardonville",
    product: "BROILER GROWER 2 MD",
    weightLbs: 9000,
    deliveryTime: "3:00 PM",
    state: "Pending",
    millLine: "CGM",
    textureType: "PELLET",
    lineCode: "22564",
  },
  // CGM Mixing (2)
  {
    id: "31",
    orderNumber: "ORD-255461",
    customer: "Cedarcroft Poultry",
    product: "BROILER STARTER MD",
    weightLbs: 12000,
    deliveryTime: "9:45 AM",
    state: "Mixing",
    millLine: "CGM",
    textureType: "C. CRUMBLE",
    lineCode: "22562",
  },
  {
    id: "32",
    orderNumber: "ORD-255352",
    customer: "Triple H Farms",
    product: "BROILER STARTER MD",
    weightLbs: 9000,
    deliveryTime: "10:15 AM",
    state: "Mixing",
    millLine: "CGM",
    textureType: "C. CRUMBLE",
    lineCode: "22562",
  },
  // CGM Blocked (1)
  {
    id: "33",
    orderNumber: "ORD-255360",
    customer: "Whytebridge Farms",
    product: "BROIL FINISH 1 PELLET WD",
    weightLbs: 18000,
    deliveryTime: "11:15 AM",
    state: "Blocked",
    millLine: "CGM",
    textureType: "PELLET",
    lineCode: "22566",
  },
];

function delay(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

export async function getProductionOrders(): Promise<ProductionOrder[]> {
  await delay(200 + Math.random() * 100);
  return mockOrders;
}

export async function getOrdersByMillLine(
  millLine: MillLine
): Promise<ProductionOrder[]> {
  await delay(200 + Math.random() * 100);
  return mockOrders.filter((order) => order.millLine === millLine);
}
