/**
 * scripts/test-xlsx-import.ts
 *
 * End-to-end dev-DB smoke harness for the XLSX import pipeline.
 * Exercises the real `@neondatabase/serverless` HTTP driver against
 * `example-data/Book1.xlsx` and asserts production_orders +
 * import_batches row count deltas.
 *
 * GAP-03 closure (33-VERIFICATION.md): Unit tests mock `@/db`; this harness
 * hits the real Neon HTTP driver so per-row auto-commit behavior and the
 * UNIQUE constraint surface on `order_number` are exercised end-to-end.
 *
 * Usage:
 *   npm run test:xlsx-import
 *   (or: npx tsx scripts/test-xlsx-import.ts)
 *
 * Prerequisites:
 *   - `.env.local` must contain `DATABASE_URL` pointing to the Neon POOLED
 *     endpoint (-pooler.neon.tech). This is the same endpoint used by the
 *     dev server (set since Phase 31).
 *   - DO NOT run against a production DATABASE_URL without first reviewing
 *     the sentinel cleanup (T-33-07-WrongDB threat — accepted for local dev).
 *
 * Why this harness duplicates action logic instead of invoking the action:
 *   The action functions (`previewImportAction`, `commitImportAction`) call
 *   `requireRole('mill_operator')` as their first statement, which in turn
 *   calls `auth()` from `@clerk/nextjs/server`. In a Node CLI context there
 *   is no HTTP request, no Clerk session cookie, and no request-scoped
 *   context object — `auth()` throws. Stubbing Clerk's `auth()` without a
 *   Next.js request harness (e.g. via @clerk/testing setupClerkTestingToken)
 *   requires the full Clerk testing infrastructure and a running Next.js
 *   process, violating scope discipline (plan 33-07 adds ONE script and ONE
 *   npm entry). The gap (GAP-03) is about driver behavior, NOT authorization
 *   semantics — the auth contract is verified by unit tests (TRANS-13 in
 *   33-06-SUMMARY.md). Direct Drizzle calls replicate the exact same SQL
 *   generated by the action and fully exercise the Neon HTTP driver path
 *   (T-33-07-NoAuth disposition: accept).
 *
 * HARNESS_CREATED_BY sentinel rationale:
 *   Every harness-inserted row sets `created_by = 'harness-xlsx-test'`.
 *   The cleanup WHERE clause uses the same sentinel as its sole filter, so
 *   production rows (seeded via 'system-seed' or real Clerk user IDs) are
 *   NEVER touched by this harness.
 *
 * Idempotency contract:
 *   Step 3 (preDeleteSentinelRows) runs BEFORE the insert loop to clear any
 *   leftover state from a prior interrupted run. The `finally` block re-runs
 *   the same deletes so every successful (and failed) run leaves zero residue.
 *
 * Decision references:
 *   - GAP-03: 33-VERIFICATION.md — live Neon HTTP driver gap
 *   - D-08:   Per-row auto-commit; no multi-statement transaction on neon-http.
 *             Partial-import is the contracted behavior (IMPORT-04).
 *   - CR-01:  weightLbs is `numeric(10,2)` on Drizzle — insert as string.
 *   - D-16:   Book1.xlsx has no Mill Line column; every row defaults to 'Premix'.
 *   - D-13:   All imports start as 'Pending'.
 */

// ── 'server-only' shim is loaded BEFORE this module via tsx --import ───────
// The harness is invoked as:
//   tsx --import ./scripts/_server-only-shim.mjs scripts/test-xlsx-import.ts
// see scripts/_server-only-shim.mjs for the rationale. The shim must run via
// --import (not an inline statement) because ESM hoists all `import`
// declarations above module-level code, so an inline shim would patch the
// resolver AFTER `import { db } from '@/db'` has already failed.

// ── Load .env.local BEFORE any import that touches src/db/index.ts ─────────
// src/db/index.ts throws immediately if process.env.DATABASE_URL is undefined.
// dotenv.config must run before the module graph is evaluated, which in ESM/tsx
// means the call must be synchronous and at the top of the file.
import { config as loadDotenv } from 'dotenv';
loadDotenv({ path: '.env.local' });

import { readFileSync } from 'node:fs';
import path from 'node:path';
import { randomUUID } from 'node:crypto';

// The `@/` alias resolves to `./src/` per tsconfig paths.
// tsx resolves tsconfig path aliases at runtime; no extra config needed.
// NOTE: `src/db/index.ts` begins with `import 'server-only'` (D-10) — the npm
// `server-only` package throws by design when imported from a non-RSC runtime
// (plain Node/tsx). The resolver hook at the top of this file short-circuits
// that import to a no-op so direct Drizzle access from this script is safe.
import { db } from '@/db';
import { productionOrders } from '@/db/schema/orders';
import { orderEvents } from '@/db/schema/events';
import { importBatches } from '@/db/schema/imports';
import { productionOrderImportSchema } from '@/actions/import-schema';
import { MAX_IMPORT_BYTES } from '@/lib/import-constants';

// read-excel-file 9.x requires a module-level import; tsx handles ESM interop.
// The type cast pattern used here matches src/actions/import.ts exactly
// (lines 123-128) to keep the two parse pipelines aligned.
import readXlsxFile from 'read-excel-file/node';

import { eq, sql } from 'drizzle-orm';

// ── Constants ────────────────────────────────────────────────────────────────

/**
 * Cleanup sentinel. Every row inserted by this harness carries this string as
 * `created_by` (production_orders) and `imported_by` (import_batches). The
 * cleanup WHERE clause is `eq(col, 'harness-xlsx-test')` — no other rows are
 * ever touched.
 *
 * production_orders.createdBy   = 'harness-xlsx-test'  (insert + cleanup WHERE)
 * order_events.changedBy        = 'harness-xlsx-test'  (insert + cleanup WHERE)
 * import_batches.importedBy     = 'harness-xlsx-test'  (insert + cleanup WHERE)
 */
const HARNESS_CREATED_BY = 'harness-xlsx-test';

/**
 * Path to the Book1.xlsx fixture. Resolved relative to the script file so it
 * works regardless of the CWD from which npm run test:xlsx-import is invoked.
 * __dirname is available because tsx compiles to CJS internally.
 */
const FIXTURE_PATH = path.resolve(__dirname, '../example-data/Book1.xlsx');

// ── XLSX Schema ──────────────────────────────────────────────────────────────
// MUST match src/actions/import.ts xlsxSchema verbatim (lines 66-76).
// If the column mapping changes in the action, update this copy and add a
// comment referencing the action commit that changed it.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
const xlsxSchema: Record<string, any> = {
  'Document Number': { prop: 'orderNumber', type: String, required: true },
  Customer:          { prop: 'customer', type: String, required: true },
  Product:           { prop: 'product', type: String, required: true },
  Weight:            { prop: 'weightLbs', type: Number, required: true },
  'Early Delivery Date': { prop: 'deliveryDate', type: Date },
  'Formula Type':    { prop: 'formulaType', type: String, required: true },
  'Texture Type':    { prop: 'textureType', type: String },
  'Line Code':       { prop: 'lineCode', type: String },
  // No 'Mill Line' key — Book1.xlsx has no Mill Line column (D-16)
};

// ── Type definitions ─────────────────────────────────────────────────────────

interface ParsedRow {
  orderNumber: string;
  customer: string;
  product: string;
  weightLbs: number;
  deliveryTime: string;
  formulaType: string;
  millLine: 'Premix' | 'Excel' | 'CGM';
  textureType: string | null;
  lineCode: string | null;
}

// ── Helper: Date → YYYY-MM-DD ────────────────────────────────────────────────
// Mirrors the private `dateToIsoString` helper in src/actions/import.ts (line 93).
function dateToIsoString(d: unknown): string {
  if (d instanceof Date && !isNaN(d.getTime())) {
    return d.toISOString().split('T')[0];
  }
  return '';
}

// ── Step 1: loadFixture ───────────────────────────────────────────────────────
function loadFixture(): Buffer {
  console.log('step 1: loadFixture ...');
  let buffer: Buffer;
  try {
    buffer = readFileSync(FIXTURE_PATH);
  } catch (err) {
    throw new Error(`Cannot read fixture at ${FIXTURE_PATH}: ${String(err)}`);
  }

  // IMPORT-07 layer 2: same byte-size guard as the action (T-33-DoS)
  if (buffer.byteLength > MAX_IMPORT_BYTES) {
    throw new Error(
      `Fixture is ${buffer.byteLength} bytes — exceeds MAX_IMPORT_BYTES (${MAX_IMPORT_BYTES}). ` +
      'Use a smaller fixture for the harness test.'
    );
  }

  console.log(`step 1: loadFixture - OK (${buffer.byteLength} bytes)`);
  return buffer;
}

// ── Step 2: parse ─────────────────────────────────────────────────────────────
async function parse(buffer: Buffer): Promise<ParsedRow[]> {
  console.log('step 2: parse ...');

  // Type cast mirrors src/actions/import.ts lines 123-128 exactly.
  type XlsxFn = (
    input: Buffer,
    options: { schema: Record<string, unknown> }
  ) => Promise<{
    rows: Record<string, unknown>[];
    errors: Array<{ row: number; column: string; error: string; value: unknown }>;
  }>;

  const { rows: rawRows, errors: parserErrors } = await (readXlsxFile as unknown as XlsxFn)(
    buffer,
    { schema: xlsxSchema }
  );

  if (parserErrors.length > 0) {
    console.warn(`  parse: ${parserErrors.length} parser error(s) in fixture:`);
    for (const pe of parserErrors) {
      console.warn(`    row ${pe.row} col "${pe.column}": ${pe.error} (value: ${String(pe.value)})`);
    }
  }

  const validRows: ParsedRow[] = [];

  for (let i = 0; i < rawRows.length; i++) {
    const raw = rawRows[i];
    // D-16: inject 'Premix' + date conversion before Zod validation
    const toValidate = {
      ...raw,
      millLine: 'Premix' as const,
      deliveryTime: dateToIsoString(raw.deliveryDate),
    };

    const parsed = productionOrderImportSchema.safeParse(toValidate);
    if (!parsed.success) {
      console.warn(`  parse: row ${i + 1} failed validation:`, parsed.error.issues);
      continue; // skip invalid rows — harness uses only clean rows
    }

    validRows.push({
      orderNumber: parsed.data.orderNumber,
      customer: parsed.data.customer,
      product: parsed.data.product,
      weightLbs: parsed.data.weightLbs,
      deliveryTime: parsed.data.deliveryTime,
      formulaType: parsed.data.formulaType,
      millLine: parsed.data.millLine,
      textureType: parsed.data.textureType ?? null,
      lineCode: parsed.data.lineCode ?? null,
    });
  }

  console.log(`step 2: parse - OK (${validRows.length} valid rows from ${rawRows.length} raw rows)`);
  return validRows;
}

// ── Step 3: preDeleteSentinelRows ─────────────────────────────────────────────
async function preDeleteSentinelRows(): Promise<void> {
  console.log('step 3: preDeleteSentinelRows ...');

  // Delete in order: order_events (FK cascade from production_orders), then
  // production_orders, then import_batches. Explicit event delete is belt-and-
  // suspenders — the CASCADE on the FK handles it automatically, but being
  // explicit confirms the FK cascade is wired correctly.
  /* eslint-disable @typescript-eslint/no-explicit-any */
  const eventsDeleted = await db.delete(orderEvents).where(eq(orderEvents.changedBy, HARNESS_CREATED_BY)).returning({ id: orderEvents.id });
  const ordersDeleted = await db.delete(productionOrders).where(eq(productionOrders.createdBy, HARNESS_CREATED_BY)).returning({ id: productionOrders.id });
  const batchesDeleted = await db.delete(importBatches).where(eq(importBatches.importedBy, HARNESS_CREATED_BY)).returning({ id: importBatches.id });
  /* eslint-enable @typescript-eslint/no-explicit-any */

  console.log(
    `step 3: preDeleteSentinelRows - deleted ${ordersDeleted.length} production_orders, ` +
    `${batchesDeleted.length} import_batches, ${eventsDeleted.length} order_events`
  );
}

// ── Step 4: snapshotCounts ────────────────────────────────────────────────────
interface Snapshot {
  ordersCount: number;
  batchesCount: number;
}

async function snapshotCounts(): Promise<Snapshot> {
  console.log('step 4: snapshotCounts ...');

  const [ordersResult] = await db
    .select({ count: sql<number>`count(*)::int` })
    .from(productionOrders);

  const [batchesResult] = await db
    .select({ count: sql<number>`count(*)::int` })
    .from(importBatches);

  const snapshot: Snapshot = {
    ordersCount: ordersResult?.count ?? 0,
    batchesCount: batchesResult?.count ?? 0,
  };

  console.log(
    `step 4: snapshot - prod_orders=${snapshot.ordersCount}, import_batches=${snapshot.batchesCount}`
  );
  return snapshot;
}

// ── Step 5: commit ────────────────────────────────────────────────────────────
interface CommitStats {
  committedCount: number;
  failedCount: number;
  batchId: string;
}

async function commit(parsedRows: ParsedRow[]): Promise<CommitStats> {
  console.log('step 5: commit ...');

  const batchId = randomUUID();
  let committedCount = 0;
  let failedCount = 0;

  for (const row of parsedRows) {
    // D-08: per-row auto-commit; no transaction wrapper (neon-http limitation)
    try {
      // INSERT productionOrders
      // CR-01: weightLbs.toString() — numeric column expects string in Drizzle
      // D-16: millLine defaults to 'Premix'
      // D-13: state defaults to 'Pending' for all new imports
      const [inserted] = await db
        .insert(productionOrders)
        .values({
          orderNumber: row.orderNumber,
          customer: row.customer,
          product: row.product,
          weightLbs: row.weightLbs.toString(), // CR-01: numeric→string at DB boundary
          deliveryTime: row.deliveryTime,
          millLine: 'Premix' as const,          // D-16
          textureType: row.textureType ?? null,
          lineCode: row.lineCode ?? null,
          state: 'Pending' as const,             // D-13
          version: 1,
          createdBy: HARNESS_CREATED_BY,         // sentinel for cleanup
        })
        .returning({ id: productionOrders.id });

      // Audit row: initial-insert event (RESEARCH.md Open Question 2 — YES)
      // fromState: null (no prior state — row is being created for the first time)
      // toState: 'Pending' (initial state)
      await db.insert(orderEvents).values({
        orderId: inserted.id,
        fromState: null,
        toState: 'Pending',
        changedBy: HARNESS_CREATED_BY,   // sentinel for cleanup
        note: 'Imported from XLSX',
      });

      committedCount++;
    } catch (err) {
      // D-08: partial-import — failed rows do not abort the loop
      console.error(`  commit: row "${row.orderNumber}" failed:`, String(err));
      failedCount++;
    }
  }

  // D-07: write import_batches row ONLY if committedCount > 0
  if (committedCount > 0) {
    await db.insert(importBatches).values({
      id: batchId,
      fileName: 'Book1.xlsx',
      rowCount: committedCount,
      importedBy: HARNESS_CREATED_BY,   // sentinel for cleanup
    });
  }

  console.log(`step 5: commit - committed=${committedCount}, failed=${failedCount}`);
  return { committedCount, failedCount, batchId };
}

// ── Step 6: assertPostConditions ──────────────────────────────────────────────
async function assertPostConditions(
  snapshot: Snapshot,
  stats: CommitStats
): Promise<boolean> {
  console.log('step 6: assertPostConditions ...');

  let passed = true;

  // Assert production_orders delta === committedCount
  const [ordersResult] = await db
    .select({ count: sql<number>`count(*)::int` })
    .from(productionOrders);
  const newOrdersCount = ordersResult?.count ?? 0;
  const ordersDelta = newOrdersCount - snapshot.ordersCount;

  if (ordersDelta !== stats.committedCount) {
    console.error(
      `  FAIL: production_orders delta=${ordersDelta} but expected committedCount=${stats.committedCount}`
    );
    passed = false;
  } else {
    console.log(`  OK: production_orders delta=${ordersDelta} === committedCount=${stats.committedCount}`);
  }

  if (stats.committedCount > 0) {
    // Assert import_batches delta === 1
    const [batchesResult] = await db
      .select({ count: sql<number>`count(*)::int` })
      .from(importBatches);
    const newBatchesCount = batchesResult?.count ?? 0;
    const batchesDelta = newBatchesCount - snapshot.batchesCount;

    if (batchesDelta !== 1) {
      console.error(
        `  FAIL: import_batches delta=${batchesDelta} but expected 1`
      );
      passed = false;
    } else {
      console.log(`  OK: import_batches delta=${batchesDelta} === 1`);
    }

    // Assert the inserted batch row has correct fields
    const batches = await db
      .select()
      .from(importBatches)
      .where(eq(importBatches.importedBy, HARNESS_CREATED_BY));

    if (batches.length === 0) {
      console.error('  FAIL: no import_batches row found for sentinel');
      passed = false;
    } else {
      const batch = batches[batches.length - 1]; // most recent
      if (batch.fileName !== 'Book1.xlsx') {
        console.error(`  FAIL: batch.fileName="${batch.fileName}" expected "Book1.xlsx"`);
        passed = false;
      } else {
        console.log(`  OK: batch.fileName="${batch.fileName}"`);
      }
      if (batch.rowCount !== stats.committedCount) {
        console.error(
          `  FAIL: batch.rowCount=${batch.rowCount} expected committedCount=${stats.committedCount}`
        );
        passed = false;
      } else {
        console.log(`  OK: batch.rowCount=${batch.rowCount} === committedCount=${stats.committedCount}`);
      }
    }

    // Assert order_events count >= committedCount (one event per inserted order)
    const [eventsResult] = await db
      .select({ count: sql<number>`count(*)::int` })
      .from(orderEvents)
      .where(eq(orderEvents.changedBy, HARNESS_CREATED_BY));
    const eventsCount = eventsResult?.count ?? 0;

    if (eventsCount < stats.committedCount) {
      console.error(
        `  FAIL: order_events count=${eventsCount} < committedCount=${stats.committedCount}`
      );
      passed = false;
    } else {
      console.log(
        `  OK: order_events count=${eventsCount} >= committedCount=${stats.committedCount}`
      );
    }
  }

  console.log(
    `step 6: assertPostConditions - ${passed ? 'PASSED' : 'FAILED'}`
  );
  return passed;
}

// ── Step 7: cleanup ──────────────────────────────────────────────────────────
// Called from the `finally` block — must succeed even after assertion failures.
async function cleanup(): Promise<void> {
  try {
    console.log('step 7: cleanup ...');

    // Delete in FK-safe order: events first, then orders, then batches.
    const eventsDeleted = await db.delete(orderEvents).where(eq(orderEvents.changedBy, HARNESS_CREATED_BY)).returning({ id: orderEvents.id });
    const ordersDeleted = await db.delete(productionOrders).where(eq(productionOrders.createdBy, HARNESS_CREATED_BY)).returning({ id: productionOrders.id });
    const batchesDeleted = await db.delete(importBatches).where(eq(importBatches.importedBy, HARNESS_CREATED_BY)).returning({ id: importBatches.id });

    console.log(
      `step 7: cleanup - deleted ${ordersDeleted.length} production_orders, ` +
      `${batchesDeleted.length} import_batches, ${eventsDeleted.length} order_events`
    );
  } catch (err) {
    console.error('step 7: cleanup FAILED (residue may remain):', String(err));
  }
}

// ── Step 8: main ─────────────────────────────────────────────────────────────
async function main(): Promise<void> {
  const buffer = loadFixture();
  const parsedRows = await parse(buffer);

  if (parsedRows.length === 0) {
    throw new Error('No valid rows parsed from fixture — cannot proceed with commit step.');
  }

  await preDeleteSentinelRows();
  const snapshot = await snapshotCounts();
  const stats = await commit(parsedRows);
  const passed = await assertPostConditions(snapshot, stats);

  if (!passed) {
    throw new Error('One or more post-condition assertions failed — see errors above.');
  }
}

// ── Top-level orchestration ──────────────────────────────────────────────────
(async () => {
  try {
    await main();
    console.log('PASS: GAP-03 closed');
    process.exit(0);
  } catch (err) {
    console.error('FAIL:', err);
    process.exitCode = 1;
  } finally {
    await cleanup();
  }
})();
